import Grid from "@xcritical/grid";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import JiraService, { JiraIssueModel } from "../../services/jira";
import { ThemeProvider } from "styled-components";

import styles from "../../styles/Home.module.css";
import { columns } from "./consts";
import theme from "../../theme";
import {
  ContentWrapper,
  GridInner,
  GridWrapper,
} from "../../components/styled";

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries. See the "Technical details" section.
export const getStaticProps: GetStaticProps = async (ctx) => {
  const issues = await JiraService.lookupTasksByVersions("17238");
  return {
    props: {
      issues,
    },
    // Next.js will attempt to re-generate the page:
    // - When a request comes in
    // - At most once every 10 seconds
    revalidate: 60, // In seconds
  };
};

const Releases: NextPage<{ issues: JiraIssueModel[] }> = ({ issues }) => {
  const [size, setSize] = useState({
    width: 0,
    height: 0,
  });
  useEffect(() => {
    setSize({
      width: document.documentElement.clientWidth - 100,
      height: document.documentElement.clientHeight - 100,
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <ContentWrapper>
          <main className={styles.main}>
            <GridWrapper>
              <GridInner height={issues.length * 37 + 40}>
                <Grid
                  rowHeight={37}
                  columns={columns}
                  items={issues}
                  shouldFitContainer
                />
              </GridInner>
            </GridWrapper>
          </main>
        </ContentWrapper>
      </ThemeProvider>
    </div>
  );
};

export default Releases;
